// <auto-generated />
using System;
using Dentor.Academy.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dentor.Academy.Web.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20251009175303_AddUserResponseTextAnswer")]
    partial class AddUserResponseTextAnswer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dentor.Academy.Web.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("option_text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_answer_options");

                    b.HasIndex("IsCorrect")
                        .HasDatabaseName("ix_answer_options_is_correct");

                    b.HasIndex("QuestionId", "OrderIndex")
                        .HasDatabaseName("ix_answer_options_question_id_order_index");

                    b.ToTable("answer_options", (string)null);
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<string>("ExplanationImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("explanation_image_url");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<decimal>("Points")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("points");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("question_text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("question_type");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("QuizId", "OrderIndex")
                        .HasDatabaseName("ix_questions_quiz_id_order_index");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("PassingScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("passing_score");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quizzes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_quizzes_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_quizzes_is_active");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_quizzes_title");

                    b.ToTable("quizzes", (string)null);
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_id");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<decimal?>("TotalPointsEarned")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_points_earned");

                    b.Property<decimal?>("TotalPointsPossible")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_points_possible");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_quiz_attempts");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_quiz_attempts_completed_at");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("ix_quiz_attempts_is_completed");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_quiz_attempts_quiz_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_quiz_attempts_started_at");

                    b.HasIndex("UserId", "QuizId")
                        .HasDatabaseName("ix_quiz_attempts_user_id_quiz_id");

                    b.ToTable("quiz_attempts", (string)null);
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.UserResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<decimal>("PointsEarned")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("points_earned");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_attempt_id");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text_answer");

                    b.HasKey("Id")
                        .HasName("pk_user_responses");

                    b.HasIndex("AnsweredAt")
                        .HasDatabaseName("ix_user_responses_answered_at");

                    b.HasIndex("IsCorrect")
                        .HasDatabaseName("ix_user_responses_is_correct");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_user_responses_question_id");

                    b.HasIndex("QuizAttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_responses_quiz_attempt_id_question_id");

                    b.ToTable("user_responses", (string)null);
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.UserResponseAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("answer_option_id");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selected_at");

                    b.Property<int>("UserResponseId")
                        .HasColumnType("integer")
                        .HasColumnName("user_response_id");

                    b.HasKey("Id")
                        .HasName("pk_user_response_answers");

                    b.HasIndex("AnswerOptionId")
                        .HasDatabaseName("ix_user_response_answers_answer_option_id");

                    b.HasIndex("UserResponseId", "AnswerOptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_response_answers_user_response_id_answer_option_id");

                    b.ToTable("user_response_answers", (string)null);
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.AnswerOption", b =>
                {
                    b.HasOne("Dentor.Academy.Web.Models.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answer_options_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.Question", b =>
                {
                    b.HasOne("Dentor.Academy.Web.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_quizzes_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.QuizAttempt", b =>
                {
                    b.HasOne("Dentor.Academy.Web.Models.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_attempts_quizzes_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.UserResponse", b =>
                {
                    b.HasOne("Dentor.Academy.Web.Models.Question", "Question")
                        .WithMany("UserResponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_responses_questions_question_id");

                    b.HasOne("Dentor.Academy.Web.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("UserResponses")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_responses_quiz_attempts_quiz_attempt_id");

                    b.Navigation("Question");

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.UserResponseAnswer", b =>
                {
                    b.HasOne("Dentor.Academy.Web.Models.AnswerOption", "AnswerOption")
                        .WithMany("UserResponseAnswers")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_response_answers_answer_options_answer_option_id");

                    b.HasOne("Dentor.Academy.Web.Models.UserResponse", "UserResponse")
                        .WithMany("UserResponseAnswers")
                        .HasForeignKey("UserResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_response_answers_user_responses_user_response_id");

                    b.Navigation("AnswerOption");

                    b.Navigation("UserResponse");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.AnswerOption", b =>
                {
                    b.Navigation("UserResponseAnswers");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizAttempts");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.QuizAttempt", b =>
                {
                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("Dentor.Academy.Web.Models.UserResponse", b =>
                {
                    b.Navigation("UserResponseAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
